#!/bin/bash

random_input=`getinput @random`
set -- $random_input
# Get the random value and convert it to index in files data set
rand1=`echo "$1" | grep -Eo '[0-9]+([.][0-9]+)?'`
rand2=`echo "$1" | grep -Eo '[0-9]+([.][0-9]+)?'`
index1=`bc <<< "scale=0; (($rand1)*100)%3" | awk '{printf("%d\n",$1)}' `
index2=`bc <<< "scale=0; (($rand2)*100)%3" | awk '{printf("%d\n",$1)}' `
files=("come.csv"  "agoue.csv"  "lokossa.csv")
outputs=("result.out"  "Result.out"  "resulT.out")
file=${files[$index1]}
output=${outputs[$index2]}

ssh_student --setup-script "bash student/start.sh student/$file"

# get the last line of file
solution=`awk -f /task/solutions/data.awk student/$file`
student=`cat /task/student/"$output"`
if [ "$solution" = "$student" ]; then
	feedback-result success
else
	feedback-result failed
    feedback-msg  -m "You answer is $student the correct answer is $solution"
fi 