#!/bin/bash

random_input=`getinput @random`
set -- $random_input
# Get the random value and convert it to index in files data set
rand1=`echo "$1" | grep -Eo '[+-]?[0-9]+([.][0-9]+)?'`
rand2=`echo "$2" | grep -Eo '[+-]?[0-9]+([.][0-9]+)?'`
index1=`bc <<< "scale=0; (($rand1)*100)%3" | awk '{printf("%d\n",$1)}' `
index2=`bc <<< "scale=0; (($rand2)*100)%3" | awk '{printf("%d\n",$1)}' `
files=("come.doc"  "agoue.avi"  "lokossa.doc")
outputs=("results.out" "Results.Out" "rEsults.out")
file=${files[$index1]}
output=${outputs[$index2]}

ssh_student --setup-script "python3 student/start.py"

# get the last line of file
solution1=`find /task/student/ -name $file`
solution2=`cd /task/student/ && find . -name $file`
solution3=`cd /task/ && find student -name $file`
student=`cat /task/student/$output`
if [ "$solution1" = "$student" ] || [ "$solution2" = "$student" ] || [ "$solution3" = "$student" ]; then
	feedback-result success
else
	feedback-result failed
    feedback-msg  -m "You have to use find $student $output $file $solution"
fi 