#!/bin/bash

random_input=`getinput @random`
set -- $random_input
# Get the random value and convert it to index in files data set
rand1=`echo "$1" | grep -Eo '[0-9]+([.][0-9]+)?'`
rand2=`echo "$2" | grep -Eo '[0-9]+([.][0-9]+)?'`
rand3=`echo "$3" | grep -Eo '[0-9]+([.][0-9]+)?'`
index1=`bc <<< "scale=0; (($rand1)*100)%7" | awk '{printf("%d\n",$1)}' `
index2=`bc <<< "scale=0; (($rand2)*100)%7" | awk '{printf("%d\n",$1)}' `
index3=`bc <<< "scale=0; (($rand3)*100)%7" | awk '{printf("%d\n",$1)}' `

softs=("software" "Software" "sOftware"  "soFtware"  "sofTware"  "softWare"  "softwAre")
paterns=("break" "alarm" "strcmp" "memcpy" "atoi"  "strsignal"  "pipe")
files=("answer.out" "Answer.out" "aNswer.out" "anSwer.out" "ansWer.out"  "ansWer.out"  "answEr.out")

soft=${softs[$index1]}
patern=${paterns[$index2]}
file=${files[$index3]}

ssh_student --setup-script "bash /task/student/start.sh /task/student/$soft"

solution=`grep -r -m 1 "$patern" /task/student/"$soft" | wc -l `
student=`cat /task/student/"$file"`

if [ "$student" = "$solution" ]; then
	feedback-result success
else
	feedback-result failed
    feedback-msg  -m "Your answer $student and the correct answer $solution"
fi 